//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WebView2.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     201
#define IDD_DIALOG_WEB_VIEW             201
#define IDD_DIALOG_CERTIFICATE          204
#define IDI_ICON_CERTIFICATE            206
#define IDI_ICON2                       207
#define IDI_ICON_PIN                    207
#define IDD_DIALOG_LLM                  210
#define IDR_MAINFRAMEL                  300
#define IDC_PROGRESS1                   1000
#define IDC_BUTTON_OK                   1001
#define IDC_BUTTON_CANCEL               1002
#define IDC_LIST1                       1003
#define IDC_LIST_CERT                   1003
#define IDC_LIST_CERTIFICATE            1003
#define IDC_STATIC_SITE_INFORMATION     1004
#define IDC_SYSLINK1                    1005
#define IDC_SYSLINK_CERTIFICATE         1005
#define IDC_STATIC_SERVICE_PROVIDER     1006
#define IDC_STATIC_SERVICE_GITHUB       1007
#define IDC_STATIC_SERVICE_GITHUB2      1008
#define IDC_BUTTON1                     1009
#define IDC_STATIC_SERVICE_GITHUB3      1010
#define IDC_STATIC_SERVICE_GITHUB4      1011
#define IDC_EDIT_ENDPOINT               1012
#define IDC_EDIT_SECRET                 1013
#define IDC_EDIT_DEPLOYMENT_NAME        1014
#define IDC_STATIC_SERVICE_GITHUB5      1015
#define IDC_STATIC_SERVICE_GITHUB6      1016
#define IDC_STATIC_SERVICE_GITHUB7      1017
#define ID_FILE_NEW_WINDOW              32771
#define ID_SCENARIO_MODALDIALOG         32775
#define ID_SCENARIO_MODELELESSDIALOG    32776
#define ID_WEBVIEW2SCENARIO_GETCOOKIES  32777
#define ID_SCENARIO_MODELESSDIALOGUSINGDIRECTCOMPOSITION 32778
#define ID_SCENARIO_INSTALLATION        32779
#define IDD_DIALOGL_PROGRESS            32780
#define IDD_DIALOG_PROGRESS             32780
#define ID_SCENARIO_CERTIFICATEDIALOG   32780
#define IDC_PROGRESS_DESCRITION         32781
#define ID_WEBVIEW2SCENARIO_GETCOOKIESFROMWININET 32781
#define ID_WEBVIEW2SCENARIO_SETCOOKIESFROMWININET 32782
#define IDC_PROGRESS_CONTROL            32783
#define ID_WEBVIEW2SCENARIO_SCRIPT      32783
#define ID_WEBVIEW2SCENARIO_OPENDEVTOOLSWINDOW 32784
#define ID_MONACOSCENARIO_OPENFILE      32785
#define ID_MONACOSCENARIO_RUN           32786
#define ID_MONACOSCENARIO_OPENCODEWITHVSCODE 32787
#define ID_VIEW_POWERSHELLOUTPUT        32788
#define ID_BUTTON32789                  32789
#define ID_MONACOSCENARIO_OPEN_VSCODE   32793
#define ID_MONACOSCENARIO_COPILOT       32794
#define ID_MONACOSCENARIO_LLMSETTINGS   32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
